
@base = http://localhost:8000/api/v1
@access = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU2NDVmYmYxLWQzMjYtNGY3MC05YzI1LTJiNjdhMzQwZGUzZCIsInR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE3NzQyNDE3MTYsImV4cCI6MTc3NDI0MjYxNn0.EDm_qnhPASKfayMe4a6DKo6yNygsZYSJXVXpPs5MRng
@refresh =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU2NDVmYmYxLWQzMjYtNGY3MC05YzI1LTJiNjdhMzQwZGUzZCIsInR5cGUiOiJyZWZyZXNoIiwiaWF0IjoxNzc0MjQxNjcwLCJleHAiOjE3NzQ4NDY0NzB9.i7bkZXD1KYG1fPx9O411tpuaXwowZRbJdz0X-qWsmEs

## auth

### register

POST {{base}}/auth/register
content-type: application/json

{
    "name": "test",
    "email": "test@test.com",
    "password": "TEst@@1234"
}

### login

POST {{base}}/auth/login
content-type: application/json

{
    "name": "test",
    "email": "test@test.com",
    "password": "TEst@@1234"
}

### refresh token

POST {{base}}/auth/refresh
content-type: application/json
Authorization: Bearer {{refresh}}

### me

GET {{base}}/auth/me
content-type: application/json
Authorization: Bearer {{access}}

### logout

POST {{base}}/auth/logout
content-type: application/json
Authorization: Bearer {{refresh}}