
@base = http://localhost:8000/api/v1
@access = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImEwNzEzNWYxLWQ4Y2MtNGQzZS04MTZiLTVlMTIyYTVkMTBhNSIsInR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE3NzQyNTAyNzgsImV4cCI6MTc3NDI1MTE3OH0.1WXe50I35YyJW31M7xHQhDB6oUdK35bQbuyFYMUsSSg
@refresh = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImEwNzEzNWYxLWQ4Y2MtNGQzZS04MTZiLTVlMTIyYTVkMTBhNSIsInR5cGUiOiJyZWZyZXNoIiwiaWF0IjoxNzc0MjQ4MDMwLCJleHAiOjE3NzQ4NTI4MzB9.FpOmEeEmMIU-t-Q_PUdi1-sJia7vL2ctPiEGluXv2JQ

## auth

### register

POST {{base}}/auth/register
content-type: application/json

{
    "name": "test",
    "email": "test@test.com",
    "password": "TEst@@1234"
}

### login

POST {{base}}/auth/login
content-type: application/json

{
    "email": "test@test.com",
    "password": "TEst@@1234"
}

### refresh token

POST {{base}}/auth/refresh
content-type: application/json
Authorization: Bearer {{refresh}}

### me

GET {{base}}/auth/me
content-type: application/json
Authorization: Bearer {{access}}

### logout

POST {{base}}/auth/logout
content-type: application/json
Authorization: Bearer {{refresh}}