
@base = http://localhost:8000/api/v1
@access = <your Access Token>
@refresh = <your Refrsh Token>

## auth

### register

POST {{base}}/auth/register
content-type: application/json

{
    "name": "test",
    "email": "test@test.com",
    "password": "TEst@@1234"
}

### login

POST {{base}}/auth/login
content-type: application/json

{
    "email": "test@test.com",
    "password": "TEst@@1234"
}

### refresh token

POST {{base}}/auth/refresh
content-type: application/json
Authorization: Bearer {{refresh}}

### me

GET {{base}}/auth/me
content-type: application/json
Authorization: Bearer {{access}}

### logout

POST {{base}}/auth/logout
content-type: application/json
Authorization: Bearer {{refresh}}


### verify

PATCH {{base}}/auth/verify
content-type: application/json
Authorization: Bearer {{access}}

{
    "id":"<Your account id>",
    "code":"<Code>"
}

### start-verification

POST {{base}}/auth/start-verification
content-type: application/json
Authorization: Bearer {{access}}

{
    "email": "test@test.com"
}


### forgot-password

POST {{base}}/auth/forgot-password
content-type: application/json
Authorization: Bearer {{access}}

{
    "email": "test@test.com"
}

### reset-password

PATCH {{base}}/auth/reset-password?id=<Your account id>
content-type: application/json
Authorization: Bearer {{access}}

{
    "code":"<code>",
    "password": "<new Password>"
}