import type { Metadata } from "next";
import type { FC, ReactNode } from "react";

import "./globals.css";
import {
	LoginButton,
	ProfileButton,
	RegisterButton,
	Show,
} from "@auth-guard/nextjs";
import MainProvider from "@/components/provider";

const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const RootLayout: FC<{
	children: ReactNode;
}> = ({ children }) => (
	<html lang="en" className="h-full antialiased">
		<body className="min-h-full flex flex-col">
			<MainProvider>
				<header className="flex items-center justify-between p-2">
					<Show when="logged-out">
						<div className="flex gap-4">
							<LoginButton mode="modal" variant="link">
								Login
							</LoginButton>
							<RegisterButton mode="modal" variant="link">
								Register
							</RegisterButton>
						</div>
					</Show>
					<Show when="logged-in">
						<ProfileButton />
					</Show>
				</header>
				{children}
			</MainProvider>
		</body>
	</html>
);

export { metadata };

export default RootLayout;
